name: 'kafkabr'
version: 1.0.2
description: Kafka Client library for Dartlang
homepage: https://coutoarmando.medium.com/
repository: https://github.com/armando-couto/kafkabr

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  quiver: ^3.2.1
  logging: ^1.1.0